# Generated by Django 3.2.3 on 2021-05-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
