# Generated by Django 3.2.3 on 2021-07-14 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(default='Company', max_length=30),
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=20)),
                ('PDescription', models.CharField(max_length=512)),
                ('PThumbnail', models.ImageField(default='package/Thumbnails/defaultTN.png', upload_to='')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAction', models.CharField(max_length=8)),
                ('LDescription', models.CharField(max_length=512)),
                ('LErrorCode', models.SmallIntegerField()),
                ('LActionStatus', models.BooleanField()),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.packages')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
