# Generated by Django 3.2.3 on 2021-07-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210714_1830'),
        ('users', '0008_userprofile_name'),
    ]

    operations = [
    ]
