# Generated by Django 3.2.3 on 2021-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210714_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='LAction',
            new_name='logAction',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='LActionStatus',
            new_name='logActionStatus',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='LDescription',
            new_name='logDesc',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='LErrorCode',
            new_name='logErrorCode',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='PID',
            new_name='pId',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='UID',
            new_name='uId',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='PDescription',
            new_name='packageDesc',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='PName',
            new_name='packageName',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='UID',
            new_name='uId',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='PThumbnail',
        ),
        migrations.AddField(
            model_name='packages',
            name='packageItems',
            field=models.FileField(default='', upload_to='package/packages'),
        ),
        migrations.AddField(
            model_name='packages',
            name='packageThumbnail',
            field=models.ImageField(default='package/thumbnails/defaultTN.png', upload_to='package/thumbnails'),
        ),
    ]
