# Generated by Django 3.2.3 on 2021-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210714_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='packageThumbnail',
            field=models.ImageField(default='package/thumbnails/defaultTN.png', height_field=320, upload_to='package/thumbnails', width_field=250),
        ),
    ]
