# Generated by Django 3.2.3 on 2021-07-15 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_alter_packages_packagethumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=20)),
                ('packageDesc', models.CharField(max_length=512)),
                ('packageThumbnail', models.ImageField(default='package/thumbnails/defaultTN.png', upload_to='package/thumbnails')),
                ('packageItems', models.FileField(default='', upload_to='package/packages')),
                ('uId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.AlterField(
            model_name='log',
            name='pId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.package'),
        ),
    ]
