# Generated by Django 3.2.3 on 2021-07-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_packages_packagethumbnail'),
        ('users', '0012_remove_packages_packageitems'),
    ]

    operations = [
    ]
