# Generated by Django 3.2.3 on 2021-07-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210715_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='packageImages',
            field=models.CharField(default='', max_length=200),
        ),
    ]
