# Generated by Django 3.2.3 on 2021-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20210715_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='packageItems',
            field=models.FileField(default='', upload_to='package/packages'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='packageThumbnail',
            field=models.ImageField(default='package/thumbnails/defaultTN.png', upload_to='package/thumbnails'),
        ),
    ]
