# Generated by Django 3.2.3 on 2021-07-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210715_1856'),
        ('users', '0014_auto_20210715_1850'),
    ]

    operations = [
    ]
